services:
  bookmarks-service:
    image: services/bookmarks-service
    build:
      context: ${BACK_ABSOLUTE_PATH}/
      dockerfile: ${BACK_ABSOLUTE_PATH}/docker/images/bookmarks-service.Dockerfile
    networks:
      - bookmarks-network
    ports:
      - "9000:9000"
    restart: on-failure
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_DB: main_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
     - bookmarks-network
    volumes:
      - ${INFRA_ABSOLUTE_PATH}/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

networks:
  bookmarks-network:
